### PR TITLE
adapted to videojs 5.x (fixes #3)

### LINKED ISSUE #3: Plug in doesn't work with latest video.js
methods for adding buttons has changed

### PR DESCRIPTION
**Pull request by miguelgrinberg**
I have adapted your plugin to work with version 5.x of videojs. Thanks for making it available!

Note that the "index" option only works with video.js >= 5.7.0. On older versions buttons are always added at the end.

### CODE REVIEW

**Comment by hexylena** [comment]
@miguelgrinberg this looks wonderful, thank you. I'd been putting this off for a while now.

**Comment by hexylena** [comment]
Adding npm + bower support as a thank you, maybe that's useful to you.

**Comment by miguelgrinberg** [comment]
Yes, definitely. I was going to do it myself, actually. Awesome!

**Comment by miguelgrinberg** [comment]
I think you also need to add a version tag in the repo for bower to work. Currently this is what happens:

```
$ bower install "videojs-framebyframe#~1.0.0"
bower videojs-framebyframe#~1.0.0       not-cached git://github.com/erasche/videojs-framebyframe.git#~1.0.0
bower videojs-framebyframe#~1.0.0          resolve git://github.com/erasche/videojs-framebyframe.git#~1.0.0
bower videojs-framebyframe#~1.0.0       not-cached git://github.com/erasche/videojs-framebyframe.git#~1.0.0
bower videojs-framebyframe#~1.0.0          resolve git://github.com/erasche/videojs-framebyframe.git#~1.0.0
bower videojs-framebyframe#~1.0.0     ENORESTARGET No tag found that was able to satisfy ~1.0.0

Additional error details:
No versions found in git://github.com/erasche/videojs-framebyframe.git
```

**Comment by hexylena** [comment]
Ah, ok, I'd only tested `bower install videojs-framebyframe`, not the pinned version. Good suggestion.

**Comment by hexylena** [comment]
Done. https://github.com/erasche/videojs-framebyframe/releases/tag/v1.0.0

**Comment by miguelgrinberg** [comment]
Fixed. Thanks!

**Pull request merged**
